apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracking-postgres-pvc
  namespace: cog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: standard
