# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tracking-postgres-service
  namespace: cog
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: tracking-postgres
  clusterIP: None # Ensures stable DNS identity
