# Default Profile
server:
  port: 8881
spring:
  application:
    name: user-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_ms_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: false
        format: yaml
        default-context: application
        profile-separator: "-"

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
# Kubernetes Profile
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://k8s-service-url:5432/catalog_db # Replace with your Kubernetes service URL
    username: k8s-user
    password: k8s-password
  cloud:
    consul:
      host: consul-service # Replace with the Consul service name in Kubernetes
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 5s
      config:
        enabled: true
        default-context: k8s-context

management:
  endpoints:
    web:
      exposure:
        include: health,info
