# Default Profile
server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8181/realms/COG}
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: false
        format: yaml
        default-context: application
        profile-separator: "-"
management:
  endpoints:
    web:
      exposure:
        include: health,info

# jwt:
#   auth:
#     converter:
#       resource-id: api-gateway
#       principle-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG