apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: cog
data:
  consul.hcl: |
    bootstrap_expect = 3
    server = true
    datacenter = "dc1"
    data_dir = "/consul/data"
    client_addr = "0.0.0.0"
    advertise_addr = "{{ GetInterfaceIP \"eth0\" }}"
    ui = true
    log_level = "INFO"
