apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: cog
spec:
  clusterIP: None
  ports:
    - port: 8500
      name: http
    - port: 8600
      name: dns
      protocol: UDP
  selector:
    app: consul
