apiVersion: v1
kind: Service
metadata:
  name: consul-nodeport
  namespace: cog
spec:
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30000
      name: http
    - port: 8600
      targetPort: 8600
      nodePort: 30001
      name: dns
      protocol: UDP
  selector:
    app: consul
  type: NodePort
