apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: cog
spec:
  serviceName: "consul"
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15.4
          ports:
            - name: http
              containerPort: 8500
            - name: dns
              containerPort: 8600
              protocol: UDP
          volumeMounts:
            - name: consul-data
              mountPath: /consul/data
            - name: consul-config
              mountPath: /consul/config/consul.hcl
              subPath: consul.hcl
          command:
            - "consul"
            - "agent"
            - "-config-file=/consul/config/consul.hcl"
          env:
            - name: CONSUL_BIND_INTERFACE
              value: "eth0"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: consul-config
          configMap:
            name: consul-config
  volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi