services:
    # Postgres SQL
  postgresql:
    container_name: cog_postgresql
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./data/pgsql:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - cog-net
    restart: unless-stopped

  # MongoDB
  mongodb:
    image: mongo
    container_name: cog_mongodb
    ports:
      - 27020:27017
    volumes:
      - ./data/mongo:/data
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - cog-net
    restart: unless-stopped

# Networks
networks:
  cog-net:
    driver: bridge